version: "3"
services:
  sp-settings:
    container_name: sp-settings
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/
    restart: always
    tty: true
    depends_on:
      - redis
    networks:
      sp-settings-net:
        ipv4_address: 172.25.0.3
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    networks:
      sp-settings-net:
        ipv4_address: 172.25.0.2

networks:
  sp-settings-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16