name: Deploy to Digital Ocean

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      # You can test your matrix by printing the current Python version
      - name: Build project
        run: pip install --no-cache-dir -r requirements.txt
      - name: Setup Environment
        run: |
          mv app/.env.example app/.env
          sed -i "s/:AUTH_HOST/${{ secrets.AUTH_HOST}}/g" app/.env
          sed -i "s/:REDIS_HOST/redis/g" app/.env
      - name: Upload project via ssh
        uses: appleboy/scp-action@master
        with:
          host: 159.65.125.31
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "./"
          target: "/usr/src/ms_settings/"
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: 159.65.125.31
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /usr/src/settings_microservices 2> /dev/null && docker-compose down;
            cd /usr/src/;
            rm settings_microservices.old 2> /dev/null;
            mv settings_microservices settings_microservices.old 2> /dev/null;
            mv ms_settings settings_microservices;
            cd settings_microservices;
            docker-compose -f docker-compose.production.yml up -d --build --force-recreate;
